#! /bin/sh

### BEGIN INIT INFO
# Provides:		deploy
# Required-Start:	
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Simple Deploying App
### END INIT INFO

set -e

DEPLOY=/home/www/deploy/deploy/process.py

# /etc/init.d/ssh: start and stop the OpenBSD "secure shell(tm)" daemon

test -x $DEPLOY || exit 0

umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_upstart() {
    if init_is_upstart; then
	exit $1
    fi
}

case "$1" in
  start)
#	check_for_upstart 1
	log_daemon_msg "Starting Simple Deploying app" "deploy" || true
	if $DEPLOY start; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
#	check_for_upstart 0
	log_daemon_msg "Stopping Simple Deploying app" "deploy" || true
	if $DEPLOY stop; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
#	check_for_upstart 1
	log_daemon_msg "Restarting Simple Deploying app" "deploy" || true
	if $DEPLOY restart; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

#  status)
#	check_for_upstart 1
#	status_of_proc -p /var/run/sshd.pid /usr/sbin/sshd sshd && exit 0 || exit $?
#	;;

  *)
	log_action_msg "Usage: $DEPLOY {start|stop|restart}" || true
	exit 1
esac

exit 0
